### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by slaxor505** [simonw/cougar-or-not#6]
I'm trying to build Docker image but I got the following error:

Step 9/11 : RUN python cougar.py
 ---> Running in e2f64e470329
Traceback (most recent call last):
  File "cougar.py", line 3, in <module>
    from fastai.vision import (
  File "/usr/local/lib/python3.6/site-packages/fastai/vision/__init__.py", line 3, in <module>
    from .learner import *
  File "/usr/local/lib/python3.6/site-packages/fastai/vision/learner.py", line 6, in <module>
    from . import models
  File "/usr/local/lib/python3.6/site-packages/fastai/vision/models/__init__.py", line 2, in <module>
    from torchvision.models import ResNet,resnet18,resnet34,resnet50,resnet101,resnet152
  File "/usr/local/lib/python3.6/site-packages/torchvision/__init__.py", line 4, in <module>
    from torchvision import datasets
  File "/usr/local/lib/python3.6/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
    from .fakedata import FakeData
  File "/usr/local/lib/python3.6/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
    from .. import transforms
  File "/usr/local/lib/python3.6/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
    from .transforms import *
  File "/usr/local/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
    from . import functional as F
  File "/usr/local/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION'
The command '/bin/sh -c python cougar.py' returned a non-zero code: 1

**Comment by hugovk** [comment]
This has been fixed in the new [torchvision 0.5.0](https://github.com/pytorch/vision/releases/tag/v0.5.0).

Please upgrade: `pip install torchvision>=0.5.0"`

**Comment by slaxor505** [comment]
@hugovk  thank you for the reply. Sorry I may be wrong but I thought that Docker build is supposed to install all required packages into image. Where should I run "pip install torchvision>=0.5.0"?

**Comment by hugovk** [comment]
I guess it's a dependency of one of these:

https://github.com/simonw/cougar-or-not/blob/8adafac571aad3385317c76bd229448b3cdaa0ac/Dockerfile#L6-L8

You could try adding `RUN pip install torchvision>=0.5.0"` there too.
